[platformio]
default_envs = um_tinys3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
; lib_deps = 4dsystems/Goldelox-Serial-Arduino-Library @ ^1.0.4
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1

[env:um_tinys3]
board = um_tinys3
